### ISSUE TITLE
Error with seed of enviroment

### ISSUE THREAD

**Issue by nanoxmaster** [kschweig/OfflineRL#3]
Hello, I was trying to reproduce your results with the instructions you gave, but when I run the first experiment I get the next error. Sorry, I'm a little newbie, could you help me?

> multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\xxxx\xxxx\OfflineRL-master\ex_01.py", line 33, in create_ds
    train_online(experiment=experiment, agent_type=behavioral, discount=discount, envid=env,
  File "C:\Users\xxxx\xxxx\OfflineRL-master\source\train_online.py", line 43, in train_online
    env.seed(seed)
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\site-packages\gym\core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\site-packages\gym\core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\site-packages\gym\core.py", line 241, in __getattr__
    return getattr(self.env, name)
AttributeError: 'CartPoleEnv' object has no attribute 'seed'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "ex_01.py", line 106, in <module>
    p.map(create_ds, range(1, multiple_useruns + 1))
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\envs\offline_rl\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: 'CartPoleEnv' object has no attribute 'seed'

**Comment by kschweig** [comment]
The issue seems to be a wrong `gym` version, the one used throughout the experiments is 0.19.
I uploaded a dump of the environment used throughout the experiments for reference.
